#!/usr/bin/env python

import os
import sys
import hostlookup

hostEntryFile = os.path.expanduser("~/.autossh/hosts")

if len(sys.argv) < 2:
    print "Usage: \n\t" + sys.argv[0] + " [target]"
    sys.exit(0)

target = sys.argv[1]

hl = hostlookup.HostLookup()
hl.loadFromFile(hostEntryFile)
ok, info = hl.get(target)
if not ok:
    print "Target not found: '%s' "%(target) 
    sys.exit(1)
print info
