#!/bin/bash

if ! test -e ~/.autossh
then
    mkdir -pv ~/.autossh
    cp -v conf/hosts.demo ~/.autossh/hosts
fi

TRAVERSE_PATH="/usr/local/bin /usr/bin /bin"
INSTALL_PATH=""
for dir in ${TRAVERSE_PATH}
do
    if test -e ${dir}
    then
        INSTALL_PATH=${dir}
        break
    fi
done

if [ "${INSTALL_PATH}"X == X ] 
then
    echo "No available install path: ${TRAVERSE_PATH}"
    echo "Install fail."
    exit 1
fi

if test -e ${INSTALL_PATH}/autossh
then
    echo "An existing install has been found at ${INSTALL_PATH}/autossh."
    echo "Remove it and run install again."
    exit 1
fi

echo "Installing to ${INSTALL_PATH} ..."

mkdir -pv ${INSTALL_PATH}/autossh
cp -fv assh ascp *.py ${INSTALL_PATH}/autossh/
ln -sfv ${INSTALL_PATH}/autossh/assh ${INSTALL_PATH}/assh
ln -sfv ${INSTALL_PATH}autossh/ascp ${INSTALL_PATH}/ascp
chmod +x ${INSTALL_PATH}/assh
chmod +x ${INSTALL_PATH}/ascp

echo "DONE"
